data:
  image: busybox
  volumes:
    - ./app/src:/usr/share/nginx/html
  # volumes_from:
  #  - data

################################################################################
# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    # - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    # - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  volumes_from:
    - data
  links:
    - php-fpm:__DOCKER_PHP_FPM__
################################################################################
# php-fpm
php-fpm:
  build: ./php-fpm
  # ports:
  #   - "9000:9000"
  volumes:
    # Your php.ini
    - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  volumes_from:
   - data
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:mysql
  # external_links:
  #   - mysql:mysql
################################################################################
# database
# alias mariadb='docker run --rm --name mariadb -p 3306:3306 -v $PWD/database/mysql:/var/lib/mysql mariadb'
mysql:
  image: mysql:latest
  # image: mariadb:latest
  ports:
  #   # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=toor
#######################################
# phpmyadmin
# alias phpmyadmin='docker run --rm --name phpmyadmin -e PMA_HOST=192.168.1.100 -p 8080:80 phpmyadmin/phpmyadmin "$@"'
# alias phpmyadmin='docker run --rm --name phpmyadmin --link mariadb:db -p 8080:80 phpmyadmin/phpmyadmin "$@"'
#######################################
# phpmyadmin:
#   image: phpmyadmin/phpmyadmin
#   ports:
#     - 8080:80
#   links:
#     - mysql:db
